## Упражнение 7.2
Реализовать быстрое преобразование Фурье (БПФ)

In [1]:
import numpy as np
PI2 = 2 * np.pi

In [2]:
def dft(ys):
    N = len(ys)
    ts = np.arange(N) / N
    freqs = np.arange(N)
    args = np.outer(ts, freqs)
    M = np.exp(1j * PI2 * args)
    amps = M.conj().transpose().dot(ys)
    return amps

def my_fft(ys):
    He = dft(ys[::2])
    Ho = dft(ys[1::2])
    ns = np.arange(len(ys))
    W = np.exp(-1j * PI2 * ns / len(ys))
    return np.tile(He, 2) + W * np.tile(Ho, 2)

def my_recursive_fft(ys):
    if len(ys) == 1:
        return ys
    He = my_fft(ys[::2])
    Ho = my_fft(ys[1::2])
    ns = np.arange(len(ys))
    W = np.exp(-1j * PI2 * ns / len(ys))
    return np.tile(He, 2) + W * np.tile(Ho, 2)

Для примера возьмём простой массив:

In [3]:
ys = [0.2,-0.5,-0.6, 0.4]
hs = np.fft.fft(ys)
hs

array([-0.5+0.j ,  0.8+0.9j, -0.3+0.j ,  0.8-0.9j])

In [4]:
dft(ys)

array([-0.5+0.00000000e+00j,  0.8+9.00000000e-01j, -0.3-2.32682892e-16j,
        0.8-9.00000000e-01j])

Разделим массив:

In [5]:
ys[::2] , ys[1::2]

([0.2, -0.6], [-0.5, 0.4])

Используем нерекурсивный метод:

In [6]:
my_fft(ys)

array([-0.5+0.0000000e+00j,  0.8+9.0000000e-01j, -0.3+1.2246468e-17j,
        0.8-9.0000000e-01j])

Теперь будем использовать рекурсивный метод:

In [7]:
my_recursive_fft(ys)

array([-0.5+0.0000000e+00j,  0.8+9.0000000e-01j, -0.3+1.2246468e-17j,
        0.8-9.0000000e-01j])

Все результаты реализаций полностью сошлись!